### ISSUE TITLE
risks of duplicate entries

### ISSUE THREAD

**Issue by rvweeren** [tikk3r/lofar-highres-widefield#9]
https://github.com/tikk3r/lofar-highres-widefield/blob/2751faf4f190b041f00a279b1f252dde681a8a04/utils/merge_directions.py#L292

Things go wrong when using with --append-to-solset if this soltset already exists. It then adds duplicate directions in the directionlist. There should be a check if the directions already exists in the source/directions table before adding it.

**Comment by tikk3r** [comment]
I think aa9de12 should fix this. It won't add direction entries if appending, only when making a new solset. This assumes the appended soltab has the same number of directions, but I don't think either this code or losoto handles soltabs having a different number of directions anyway.

**Comment by rvweeren** [comment]
Yes, this should do it.
